// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA8TL2iK1O2r9WNVRq7vRUZnSp2VrM8RA',
    appId: '1:1040166340050:android:724df39b73811e28c6340b',
    messagingSenderId: '1040166340050',
    projectId: 'plug-in-6f160',
    storageBucket: 'plug-in-6f160.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIXIMYpfEIwE8XjTaKUahwvECFN8GMGTQ',
    appId: '1:1040166340050:ios:b2144283a14ce450c6340b',
    messagingSenderId: '1040166340050',
    projectId: 'plug-in-6f160',
    storageBucket: 'plug-in-6f160.appspot.com',
    androidClientId: '1040166340050-3geis6ul5jnhpnq03rciv15alb0m0sup.apps.googleusercontent.com',
    iosClientId: '1040166340050-3p8r42j2ogpnp2lofk64sk29gan10om4.apps.googleusercontent.com',
    iosBundleId: 'com.example.plugIn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIXIMYpfEIwE8XjTaKUahwvECFN8GMGTQ',
    appId: '1:1040166340050:ios:b2144283a14ce450c6340b',
    messagingSenderId: '1040166340050',
    projectId: 'plug-in-6f160',
    storageBucket: 'plug-in-6f160.appspot.com',
    androidClientId: '1040166340050-3geis6ul5jnhpnq03rciv15alb0m0sup.apps.googleusercontent.com',
    iosClientId: '1040166340050-3p8r42j2ogpnp2lofk64sk29gan10om4.apps.googleusercontent.com',
    iosBundleId: 'com.example.plugIn',
  );
}
